"""Built-in word list: common 5-letter English words for Wordle.

All words are exactly 5 characters, uppercase, ASCII-only.
Words containing 'Q' are excluded so the answer is always typeable
(the player uses 'q' to quit, so 'q' can never be a guess letter).
"""
from __future__ import annotations

# fmt: off
WORDS: tuple[str, ...] = (
    "ABOUT", "ABOVE", "ABUSE", "ACTOR", "ACUTE", "ADMIT", "ADOPT", "ADULT",
    "AFTER", "AGAIN", "AGENT", "AGREE", "AHEAD", "ALARM", "ALBUM", "ALERT",
    "ALIKE", "ALIVE", "ALLEY", "ALLOT", "ALLOW", "ALLOY", "ALONE", "ALONG",
    "ALTER", "ANGEL", "ANGER", "ANGLE", "ANGRY", "ANIME", "ANKLE", "ANNEX",
    "ANTIC", "ANVIL", "APART", "APPLE", "APPLY", "APRIL", "APRON", "APTLY",
    "ARENA", "ARGUE", "ARISE", "ARMOR", "AROMA", "AROSE", "ARRAY", "ARROW",
    "ASIDE", "ASSET", "ATLAS", "ATTIC", "AUDIO", "AUDIT", "AVAIL", "AVOID",
    "AWAKE", "AWARD", "AWFUL", "BADLY", "BAKER", "BASIC", "BASIN", "BASIS",
    "BATCH", "BEACH", "BEGAN", "BEGIN", "BEING", "BELOW", "BENCH", "BERRY",
    "BIRTH", "BISON", "BITER", "BLACK", "BLADE", "BLAME", "BLAND", "BLANK",
    "BLAST", "BLAZE", "BLEED", "BLEND", "BLIND", "BLOCK", "BLOOD", "BLOOM",
    "BLOWN", "BLUES", "BOARD", "BOAST", "BOXER", "BRACE", "BRAIN", "BRAND",
    "BRAVE", "BREAD", "BREAK", "BREED", "BRICK", "BRIDE", "BRIEF", "BRING",
    "BRINK", "BROIL", "BROKE", "BROOD", "BROWN", "BROWS", "BRUSH", "BUDDY",
    "BUILD", "BUILT", "BULGE", "BUNCH", "BURNS", "BURST", "BUYER", "BYLAW",
    "CABIN", "CAMEL", "CANDY", "CARRY", "CATCH", "CAUSE", "CEDAR", "CHAIN",
    "CHAIR", "CHALK", "CHAOS", "CHARM", "CHART", "CHASE", "CHEAP", "CHECK",
    "CHEEK", "CHEER", "CHESS", "CHEST", "CHIEF", "CHILD", "CHINA", "CHOIR",
    "CHORD", "CHOSE", "CIVIC", "CIVIL", "CLAIM", "CLAMP", "CLASH", "CLASP",
    "CLASS", "CLEAN", "CLEAR", "CLERK", "CLICK", "CLIFF", "CLIMB", "CLING",
    "CLOCK", "CLONE", "CLOSE", "CLOTH", "CLOUD", "CLOWN", "COACH", "COAST",
    "COMET", "COMIC", "CORAL", "COUCH", "COUNT", "COURT", "COVER", "CRAFT",
    "CRANE", "CRASH", "CRAZY", "CREAM", "CREEK", "CRISP", "CROSS", "CROWD",
    "CROWN", "CRUSH", "CRUST", "CURVE", "CYCLE", "DAILY", "DAIRY", "DANCE",
    "DATUM", "DEALS", "DEATH", "DEBUG", "DECAY", "DECOY", "DELAY", "DELTA",
    "DEMON", "DENSE", "DEPOT", "DEPTH", "DERBY", "DEVIL", "DIARY", "DIGIT",
    "DISCO", "DITCH", "DIVER", "DIZZY", "DOLLY", "DONOR", "DOUBT", "DOUGH",
    "DRAFT", "DRAIN", "DRAMA", "DRAPE", "DRAWL", "DRAWN", "DREAM", "DRILL",
    "DRINK", "DRIVE", "DROVE", "DROWN", "DRYER", "DYING", "EAGLE", "EARLY",
    "EARTH", "EIGHT", "ELECT", "EMAIL", "EMBER", "EMPTY", "ENDED", "ENJOY",
    "ENTER", "ENTRY", "ERROR", "ETHIC", "EVADE", "EVENS", "EVENT",
    "EVERY", "EXACT", "EXILE", "EXIST", "EXTRA", "FABLE", "FACET", "FAITH",
    "FALSE", "FANCY", "FATAL", "FAVOR", "FEAST", "FENCE", "FETCH", "FEVER",
    "FIELD", "FIEND", "FIFTH", "FIFTY", "FIGHT", "FINAL", "FIRST", "FIXED",
    "FJORD", "FLAME", "FLASH", "FLASK", "FLESH", "FLOAT", "FLOCK", "FLOOD",
    "FLOOR", "FLOUR", "FLUID", "FLUTE", "FOCUS", "FORAY", "FORCE", "FORGE",
    "FORTH", "FORUM", "FOUND", "FRAME", "FRANK", "FRAUD", "FRONT", "FROST",
    "FROZE", "FRUIT", "FULLY", "FUNNY", "GAVEL", "GIDDY", "GIVEN", "GLAND",
    "GLARE", "GLASS", "GLEAM", "GLIDE", "GLOSS", "GLOVE", "GOING", "GRAND",
    "GRANT", "GRASP", "GRASS", "GRAVE", "GREAT", "GREEN", "GRIEF", "GRIND",
    "GROAN", "GROPE", "GROSS", "GROUP", "GROVE", "GROWN", "GUARD", "GUESS",
    "GUEST", "GUIDE", "GUILD", "GUILT", "GUISE", "GUSTO", "GYPSY", "HABIT",
    "HANDY", "HAPPY", "HARSH", "HASTE", "HAVEN", "HEART", "HEAVY", "HEDGE",
    "HELIX", "HELLO", "HERBS", "HERON", "HILLY", "HINGE", "HIPPO", "HOBBY",
    "HOLLY", "HOMER", "HONOR", "HORSE", "HOTEL", "HOUND", "HOUSE", "HUMAN",
    "HUMOR", "HURRY", "IMAGE", "IMPLY", "INDEX", "INFER", "INNER", "INPUT",
    "INTER", "INTRO", "IRONY", "ISSUE", "IVORY", "JAPAN", "JEWEL", "JOINT",
    "JOKER", "JUDGE", "JUICE", "JUICY", "JUMBO", "KARMA", "KAYAK", "KEBAB",
    "KNEEL", "KNIFE", "KNOCK", "KNOWN", "LABEL", "LANCE", "LARGE", "LATCH",
    "LATER", "LAUGH", "LAYER", "LEARN", "LEDGE", "LEGAL", "LEMON", "LEVEL",
    "LIGHT", "LILAC", "LIMIT", "LINGO", "LINKS", "LIVER", "LOCAL", "LODGE",
    "LOGIC", "LOFTY", "LOGIN", "LOLLY", "LOVER", "LOWER", "LUCID", "LUCKY",
    "LUNAR", "LYRIC", "MAGIC", "MAJOR", "MAKER", "MANGO", "MANOR", "MAPLE",
    "MARCH", "MATCH", "MAYOR", "MEDIA", "MERGE", "MERIT", "METAL", "METER",
    "MIDST", "MIGHT", "MINOR", "MINUS", "MIRTH", "MIXED", "MODEL", "MONEY",
    "MONTH", "MORAL", "MOTEL", "MOTIF", "MOTOR", "MOURN", "MOVED", "MOVIE",
    "MUSIC", "NAIVE", "NERVE", "NEVER", "NIGHT", "NINJA", "NOBLE", "NOISE",
    "NORTH", "NOTED", "NOVEL", "NURSE", "NYMPH", "OASIS", "OCEAN", "OFFER",
    "OFTEN", "OLIVE", "ONSET", "ORBIT", "ORDER", "OTHER", "OUTDO", "UTTER",
    "OWNED", "OWNER", "OXIDE", "OZONE", "PAINT", "PANEL", "PANIC", "PAPER",
    "PARKA", "PARTY", "PASTA", "PATCH", "PAUSE", "PEACE", "PEARL", "PEDAL",
    "PENNY", "PERIL", "PERKY", "PHASE", "PHONE", "PHOTO", "PIANO", "PIECE",
    "PILOT", "PINCH", "PIXEL", "PIVOT", "PIXIE", "PIZZA", "PLACE", "PLAIN",
    "PLANE", "PLANT", "PLASM", "PLATE", "PLEAD", "PLAZA", "PLUCK", "PLUMB",
    "PLUME", "PLUNK", "PLUSH", "POINT", "POKER", "POLAR", "POPPY", "PORCH",
    "POWER", "PRESS", "PRICE", "PRIDE", "PRIME", "PRIOR", "PRIZE", "PROOF",
    "PROUD", "PROVE", "PROWL", "PRUNE", "PULSE", "PUNCH", "PUPIL", "PURGE",
    "PUSHY", "RACER", "RADAR", "RADIO", "RAISE", "RALLY", "RANCH", "RAPID",
    "RATIO", "REACH", "REBEL", "REIGN", "RELAX", "RELAY", "REALM", "RENEW",
    "REPAY", "REPEL", "REPOT", "RERUN", "RIDER", "RIDGE", "RIFLE", "RISKY",
    "RIVAL", "RIVER", "ROBOT", "ROCKY", "ROMAN", "ROUGH", "ROUND", "ROUTE",
    "ROYAL", "RUGBY", "RULER", "RUSTY", "SABER", "SADLY", "SAINT", "SALAD",
    "SAUCE", "SAVOR", "SCALE", "SCALD", "SCARE", "SCENE", "SCONE", "SCOOP",
    "SCORE", "SCOUT", "SCOWL", "SCRUB", "SEIZE", "SENSE", "SERVE", "SETUP",
    "SEVEN", "SHADE", "SHAFT", "SHAKE", "SHAKY", "SHALL", "SHAWL", "SHEEN",
    "SHEET", "SHELF", "SHIFT", "SHINE", "SHIRT", "SHOCK", "SHORE", "SHARP",
    "SHORT", "SHOUT", "SHOVE", "SHRUB", "SIREN", "SIXTH", "SIXTY", "SIZED",
    "SKILL", "SKIMP", "SKIRT", "SKULL", "SLANT", "SLATE", "SLAVE", "SLEEP",
    "SLEET", "SLICE", "SLIDE", "SLIME", "SLING", "SMART", "SMEAR", "SMELL",
    "SMILE", "SMOKE", "SNACK", "SNAIL", "SNAKE", "SNEAK", "SOLVE",
    "SORRY", "SOUTH", "SPARE", "SPARK", "SPEAR", "SPEND", "SPICE", "SPILL",
    "SPINE", "SPITE", "SPLIT", "SPOKE", "SPOON", "SPORT", "SPRAY", "STAFF",
    "STAGE", "STAIN", "STAIR", "STAMP", "STAND", "START", "STASH", "STATE",
    "STEAM", "STEEL", "STEEP", "STERN", "STICK", "STING", "STOCK", "STOMP",
    "STONE", "STOOD", "STORE", "STORK", "STORM", "STORY", "STOUT", "STOVE",
    "STRAP", "STRAW", "STRAY", "STRIP", "STRUT", "STUDY", "STUNT", "STYLE",
    "SUGAR", "SUITE", "SUNNY", "SUPER", "SURGE", "SWAMP", "SWEAR", "SWEEP",
    "SWEET", "SWIFT", "SWIPE", "SWIRL", "SWOOP", "SWORD", "TABLE", "TASTE",
    "TAUNT", "TAWNY", "TEACH", "TENSE", "TERMS", "THEIR", "THEME", "THERE",
    "THESE", "THICK", "THIRD", "THORN", "THOSE", "THREE", "THREW", "THROW",
    "TIGER", "TILED", "TIMER", "TIPSY", "TITAN", "TITLE", "TOAST", "TODAY",
    "TOKEN", "TOOTH", "TOPIC", "TORCH", "TOTAL", "TOUCH", "TOUGH", "TOWER",
    "TOWEL", "TRACE", "TRACK", "TRADE", "TRAIL", "TRAIN", "TRAIT", "TRAMP",
    "TRASH", "TREND", "TRIAL", "TRIBE", "TRICK", "TRIED", "TROOP", "TROVE",
    "TRUCK", "TRULY", "TRUMP", "TRUNK", "TRUST", "TRUTH", "TULIP", "TWICE",
    "TWIRL", "TWIST", "ULTRA", "UNCLE", "UNDER", "UNFIT", "UNITY", "UNTIL",
    "UPPER", "UPSET", "URBAN", "USAGE", "VALOR", "VALVE", "VAPOR", "VAULT",
    "VERSE", "VICAR", "VIDEO", "VIGOR", "VIRAL", "VITAL", "VIVID", "VOCAL",
    "VOICE", "VOTER", "WAIST", "WATCH", "WATER", "WEARY", "WEAVE", "WEDGE",
    "WEEDY", "WEIRD", "WHALE", "WHEAT", "WHEEL", "WHERE", "WHILE", "WHICH",
    "WHITE", "WHOLE", "WHOSE", "WIDER", "WIELD", "WITCH", "WITTY", "WORLD",
    "WORRY", "WORSE", "WORST", "WORTH", "WOUND", "WRATH", "WRIST", "WROTE",
    "YACHT", "YEARN", "YIELD", "YOUNG", "YOURS", "YOUTH", "ZEBRA", "ZESTY",
)
# fmt: on


def validate_word_list() -> None:
    """Raise ValueError if any entry is not exactly 5 uppercase ASCII letters."""
    for word in WORDS:
        if len(word) != 5 or not word.isalpha() or not word.isupper():
            raise ValueError(f"Invalid word list entry: {word!r}")
        if "Q" in word:
            raise ValueError(f"Word list must not contain Q (reserved for quit): {word!r}")
